name: Lint

on:
  push:
  pull_request:

jobs:
  install:
    name: Install Deno
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

  lint:
    needs: install
    name: Deno Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Run linter
        run: |
          cd src
          deno lint

  fmt:
    needs: install
    name: Deno Format
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check Formatting
        run: |
          cd src
          deno fmt --check
